# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=200)),
                ('auctionTitle', models.CharField(max_length=600)),
                ('description', models.CharField(max_length=2500)),
                ('currentPrice', models.FloatField(blank=True, null=True)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
