# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20170930_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='newPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
