# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auction_newprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='newPrice',
            field=models.FloatField(null=True),
        ),
    ]
